import Head from "next/head";
import { useQuery } from "urql";
import { PRODUCT_QUERY } from "../lib/query";
import Products from "./components/Products";
import { Gallery } from "../styles/Gallery";
import Welcome from "./components/Welcome";
import Quality from "./components/Quality";
import Featured from "./components/Featured";
import More from "./components/More";
import Promos from "./components/Promos";

export default function Home() {
  // fetch products from strapi backend
  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;

  if (fetching) {
    return <p>Loading...</p>;
  }
  if (error) {
    return <p>Oops could not fetch data: {error.message}</p>;
  }

  const products = data.products.data;
  // console.log(products);

  return (
    <div>
      <Head>
        <title>FarmHub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Welcome />
        <Featured />
        <Gallery>
          {
            // filter and display first 5 products
            (products || []).slice(0, 5).map((product) => (
              <Products key={product.attributes.slug} product={product} />
            ))
          }

          <More />
        </Gallery>
        <Quality />
        <Promos />
      </main>
    </div>
  );
}
