import Head from "next/head";
import { useQuery } from "urql";
import { PRODUCT_QUERY } from "../lib/query";
import Products from "./components/Products";
import { Gallery } from "../styles/Gallery";
import Welcome from "./components/Welcome";

export default function Home() {
  // fetch products from strapi backend
  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;

  if (fetching) {
    return <p>Loading...</p>;
  }
  if (error) {
    return <p>Oops could not fetch data: {error.message}</p>;
  }

  const products = data.products.data;
  // console.log(products);

  return (
    <div>
      <Head>
        <title>Drip Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Welcome />
        <Gallery>
          {products.map((product) => (
            <Products key={product.attributes.slug} product={product} />
          ))}
        </Gallery>
      </main>
    </div>
  );
}
